<a href="https://colab.research.google.com/github/anoushazaidii/Data-Science-Analytics/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# We import NumPy into Python
import numpy as np

# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# Let's print the ndarray we just created using the print() command
print('x = ', x)

x =  [1 2 3 4 5]


In [ ]:
# We create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])

# We print x
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [ ]:
# We create a rank 1 ndarray from a Python list that contains integers and strings
x = np.array([1, 2, 'World'])

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  ['1' '2' 'World']

x has dimensions: (3,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


In [ ]:
# We create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y has a total of', Y.size, 'elements')
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [ ]:
# We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

# We print x
print()
print('x = ', x)
print()

# We print the dtype x
print('The elements in x are of type:', x.dtype)


x =  [1 2 3 4 5]

The elements in x are of type: int64


In [ ]:
    #Creating NumPy ndarrays
#import numpy package
import numpy as np
uni_list=np.array(['MUET','KU','Fast','NUST'])

In [ ]:
print(uni_list)

['MUET' 'KU' 'Fast' 'NUST']


In [ ]:
type(uni_list)

numpy.ndarray

In [ ]:
#attributes of numpy array
#dtype
uni_list.dtype

dtype('<U4')

In [ ]:
import numpy as np
list_students=np.array([1,37,55,61])

In [ ]:
print(list_students)

[ 1 37 55 61]


In [ ]:
type(list_students)

numpy.ndarray

In [ ]:
list_students.dtype

dtype('int64')

In [ ]:
list_students.shape

(4,)

In [ ]:
#using nested python list let's create a 2D array
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array_2d.shape

(3, 3)

In [ ]:
array_2d.size

9

In [ ]:
list_students

array([ 1, 37, 55, 61])

In [ ]:
#accessing elements using index numbers
print("1st element : ",list_students[0])
print("2nd element : ",list_students[1])
print("Last element : ",list_students[-1])

1st element :  1
2nd element :  37
Last element :  61


In [ ]:
#changing element of 1d array
list_students[0]=10
#changing elements in rank 2 array (2d array)
array_2d[0][1]=100
#or
#changing elements in rank 2 array (2d array)
array_2d[0,1]=100

In [ ]:
print(list_students)
print("\n")
print(array_2d)

[10 37 55 61]


[[  1 100   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
print("Element at (0,0) : ",array_2d[0,0])
print("Element at (0,1) : ",array_2d[0,1])
print("Element at (0,2) : ",array_2d[0,2])

Element at (0,0) :  1
Element at (0,1) :  100
Element at (0,2) :  3


In [ ]:
#deleting an element of an array (rank 1 array)
list_students=np.delete(list_students,1)
#deleting an element of an array (rank 2 array)
array_2d=np.delete(array_2d,1,axis=0)
array_2d=np.delete(array_2d,1,axis=1)

In [ ]:
list_students=[1,2,3,55,60,66]

In [ ]:
list_students[:3]

[1, 2, 3]

In [ ]:
import numpy as np
s_list=np.array([1,2,3,4,5,6])

In [ ]:
s_list

array([1, 2, 3, 4, 5, 6])

In [ ]:
type(s_list)

numpy.ndarray

In [ ]:
s_list.dtype

dtype('int64')

In [ ]:
s_list.shape

(6,)

In [ ]:
array2=np.array(["hello", 2,3,4])

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
array2.dtype

dtype('<U21')

In [ ]:
array2=np.array([1,2,3,3.4,5.6], dtype=np.int64)

In [ ]:
array2.dtype

dtype('int64')

In [ ]:
array2

array([1, 2, 3, 3, 5])

In [ ]:
array2d=np.array([[1,2],[3,4,5]])

<ipython-input-43-9c29a4b4526f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array2d=np.array([[1,2],[3,4,5]])


In [ ]:
array2d.shape

(2,)

## Built in functions in NumPy library

In [ ]:
import numpy as np

In [ ]:
# We create a 3 x 4 ndarray full of zeros.
X = np.zeros((3,4))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [ ]:
# We create a 3 x 2 ndarray full of ones.
X = np.ones((3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [ ]:
# We create a 2 x 3 ndarray full of fives.
X = np.full((2,3), 5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


A fundamental array in Linear Algebra is the Identity Matrix. An Identity matrix is a square matrix that has only 1s in its main diagonal and zeros everywhere else. The function np.eye(N) creates a square N x N ndarray corresponding to the Identity matrix. Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument. Let's see an example:

In [ ]:
# We create a 5 x 5 Identity matrix.
X = np.eye(5)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


 We can also create diagonal matrices by using the np.diag() function. A diagonal matrix is a square matrix that only has values in its main diagonal. The np.diag() function creates an ndarray corresponding to a diagonal matrix , as shown in the example below:

In [ ]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print()
print('X = \n', X)
print()


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]



### NumPy arange function

In [ ]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)
# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [ ]:
#np.arange(start,stop,step)
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


Even though the np.arange() function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function np.linspace(). The np.linspace(start, stop, N) function returns N evenly spaced numbers over the closed interval [start, stop]. This means that both the start and thestop values are included. We should also note the np.linspace() function needs to be called with at least two arguments in the form np.linspace(start,stop). In this case, the default number of elements in the specified interval will be N= 50. The reason np.linspace() works better than the np.arange() function, is that np.linspace() uses the number of elements we want in a particular interval, instead of the step between values. Let's see some examples:

### NumPy- linespace function

In [ ]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0,25,10)

# We print the ndarray
print()
print('x = \n', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [ ]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25,
# with 25 excluded.
x = np.linspace(0,25,10, endpoint = False)

# We print the ndarray
print()
print('x = ', x)
print()

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


### NumPy - reshape function

In [ ]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print()
print('Original x = ', x)
print()

# We reshape x into a 4 x 5 ndarray
x = np.reshape(x, (4,5))

# We print the reshaped x
print()
print('Reshaped x = \n', x)
print()

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


One great feature about NumPy, is that some functions can also be applied as methods. This allows us to apply different functions in sequence in just one line of code. ndarray methods are similar to ndarray attributes in that they are both applied using dot notation (.). Let's see how we can accomplish the same result as in the above example, but in just one line of code:

In [ ]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [ ]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


In [ ]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
X = np.random.random((3,3))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)


X = 
 [[0.11886448 0.79182891 0.17941979]
 [0.18300446 0.78316562 0.19944014]
 [0.78789217 0.45369283 0.94642767]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [ ]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[12 12]
 [ 6 10]
 [10  5]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


## Accessing elements in an ndarray
the elements of an ndarray can be accessed or modified by indexing. Elements can be accessed using indices inside square brackets, [ ]. NumPy allows you to use both positive and negative indices to access elements in the ndarray. Positive indices are used to access elements from the beginning of the array, while negative indices are used to access elements from the end of the array

In [ ]:
# We create a rank 1 ndarray that contains integers from 1 to 5
x = np.array([1, 2, 3, 4, 5])

# Let's access some elements with positive indices
print('This is First Element in x:', x[0])
print('This is Second Element in x:', x[1])
print('This is Fifth (Last) Element in x:', x[4])
print()

# Let's access the same elements with negative indices
print('This is First Element in x:', x[-5])
print('This is Second Element in x:', x[-4])
print('This is Fifth (Last) Element in x:', x[-1])

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5

This is First Element in x: 1
This is Second Element in x: 2
This is Fifth (Last) Element in x: 5


## NumPy - Delete function

In [ ]:
import numpy as np

In [ ]:
#rank 1 ndarray
x1=np.array([1,2,3,4,5])
x1

array([1, 2, 3, 4, 5])

In [ ]:
#delete first element
x1=np.delete(x1,0)

array([2, 3, 4, 5])

In [ ]:
#rank 2 ndarray
x2=np.arange(1,10).reshape(3,3)

In [ ]:
x2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#delete 0th row
x2=np.delete(x2,0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
#delete 0th and 2nd column
x2=np.delete(x2,[0,2], axis=1)

array([[2],
       [5],
       [8]])

## NumPy - append function

In [ ]:
# We create a rank 1 ndarray
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We delete the first and last element of x
x = np.delete(x, [0,4])

# We print x with the first and last element deleted
print()
print('Modified x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We delete the first row of y
w = np.delete(Y, 0, axis=0)

# We delete the first and last column of y
v = np.delete(Y, [0,2], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]

Original Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


In [ ]:
rank1Array=np.array([1,2,3,4,5])

In [ ]:
rank1Array

array([1, 2, 3, 4, 5])

In [ ]:
#append an element in the above rank 1 array
rank1Array=np.append(rank1Array,6)

In [ ]:
rank1Array

array([1, 2, 3, 4, 5, 6])

In [ ]:
rank2Array=np.array([[1,2],[3,4],[5,6]])

In [ ]:
rank2Array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#add a new row`
rank2Array=np.append(rank2Array, [[7,8]], axis=0)

In [ ]:
rank2Array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#add new column
rank2Array=np.append(rank2Array, [[0],[0],[0],[0]], axis=1)

In [ ]:
rank2Array

array([[1, 2, 0],
       [3, 4, 0],
       [5, 6, 0],
       [7, 8, 0]])

In [ ]:
rank2Array=np.delete(rank2Array, [0,1], axis=0)

In [ ]:
rank2Array

array([[5, 6, 0],
       [7, 8, 0]])

## NumPy - Insert function

In [ ]:
rank2Array

array([[5, 6, 0],
       [7, 8, 0]])

In [ ]:
rank2Array=np.insert(rank2Array,1, [1,1,1], axis=0)

In [ ]:
rank2Array

array([[5, 6, 0],
       [1, 1, 1],
       [7, 8, 0]])

In [ ]:
rank2Array=np.insert(rank2Array,1, 5, axis=1)

In [ ]:
rank2Array

array([[5, 5, 6, 0],
       [1, 5, 1, 1],
       [7, 5, 8, 0]])

In [ ]:
# We create a rank 1 ndarray
x = np.array([1,2])

# We create a rank 2 ndarray
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y.
w = np.hstack((Y,x.reshape(2,1)))

# We print z
print('Vertical Stacking')
print('z = \n', z)

# We print w
print('Horizontal Stacking')
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]
Vertical Stacking
z = 
 [[1 2]
 [3 4]
 [5 6]]
Horizontal Stacking
w = 
 [[3 4 1]
 [5 6 2]]


In [ ]:
import numpy as np
list1=np.array([1,2,3.4,4.5])

In [ ]:
type(list1)

numpy.ndarray

In [ ]:
list1.dtype

dtype('float64')

In [ ]:
list1

array([1. , 2. , 3.4, 4.5])

In [ ]:
list2=np.array([1,2,3,"Hello","python"])

In [ ]:
list2.dtype

dtype('<U21')

In [ ]:
list2

array(['1', '2', '3', 'Hello', 'python'], dtype='<U21')

In [ ]:
list4=np.array([1,2,3,4.5], dtype=int)

In [ ]:
list4

array([1, 2, 3, 4])

In [ ]:
list4.dtype

dtype('int64')

In [ ]:
np.save("list4_data",list4)

In [ ]:
y=np.load('/content/list4_data.npy')

In [ ]:
y

array([1, 2, 3, 4])

In [ ]:
x=np.array([1,2,3,4,5])

In [ ]:
np.save('x_data', x)

In [ ]:
y=np.load('/content/x_data.npy')

In [ ]:
y

array([1, 2, 3, 4, 5])

#Slicing ndarrays

In [ ]:
rank1_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slicing from index 2 to index 6 (exclusive)
sliced_array = rank1_array[2:6]

print("Original Rank 1 Array:", rank1_array)
print("Sliced Array:", sliced_array)

Original Rank 1 Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliced Array: [3 4 5 6]


In [ ]:

# Create a rank 2 array
rank2_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing rows from index 1 to end and columns from index 1 to end
sliced_array = rank2_array[1:, 1:]

print("Original Rank 2 Array:\n", rank2_array)
print("Sliced Array:\n", sliced_array)

Original Rank 2 Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced Array:
 [[5 6]
 [8 9]]


In [ ]:
rank1_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slicing every other element from index 1 to end
sliced_array = rank1_array[1::2]

print("Original Rank 1 Array:", rank1_array)
print("Sliced Array:", sliced_array)

Original Rank 1 Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliced Array: [ 2  4  6  8 10]


In [ ]:
# Create a rank 1 array
rank1_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slicing last 3 elements using negative indices
sliced_array = rank1_array[-3:]

print("Original Rank 1 Array:", rank1_array)
print("Sliced Array:", sliced_array)

Original Rank 1 Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliced Array: [ 8  9 10]
